server:
  port: 8082
spring:
  application:
    name: reservation-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  registerWithEureka: true
  fetchRegistry: true

management:
  info:
    env:
      enabled: true
  endpoints:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      exposure:
        include: "*"
      health:
        show-details: always
      beans:
        enabled: true

info:
  application:
    name: ${spring.application.name}
    description: '@project.description@'
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'